-- 코드를 입력하세요.
# SELECT FIRST_HALF.FLAVOR , SUM(FIRST_HALF.TOTAL_ORDER+JULY.TOTAL_ORDER)  
# FROM JULY
# INNER JOIN FIRST_HALF 
# USING(SHIPMENT_ID)
# GROUP BY FLAVOR 
# ORDER BY (FIRST_HALF.TOTAL_ORDER+JULY.TOTAL_ORDER) DESC
# LIMIT 3


SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF
INNER JOIN (SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER  FROM JULY GROUP BY FLAVOR) AS JULY
USING(SHIPMENT_ID)
GROUP BY FIRST_HALF.FLAVOR 
ORDER BY (FIRST_HALF.TOTAL_ORDER+JULY.TOTAL_ORDER) DESC
LIMIT 3

# SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) FROM JULY GROUP BY FLAVOR




